
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({children}) {
    return (

        <div className="wrapper bg-primary-light dark:bg-primary-dark text-text-light dark:text-text-dark">
            
            <Navbar />
            {children}
            <Footer />
        </div>
    );
  }


