import { Poppins } from "next/font/google";
import "./globals.css";
import AuthProvider from "./providers/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <main >
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
